export default [
  {
    idx: 1,
    status: "",
    category: "一般",
    title: "テストタイトル",
    created_at: "21.01.07",
    donor: "testId",
    view_cnt: 3,
    like_quantity: 7,
    comment_cnt: 4,
  },
  {
    idx: 2,
    status: "",
    category: "一般",
    title: "テストタイトル",
    created_at: "21.01.07",
    donor: "testId",
    view_cnt: 3,
    like_quantity: 7,
    comment_cnt: 0,
  },
  {
    idx: 3,
    status: "",
    category: "アラム",
    title:
      "テストタイトルタイトルタイトルタイイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタトル",
    created_at: "21.01.07",
    donor: "testIdtestIdtestIdtestIdtestIdtestIdtestIdtestIdtestIdtestIdtestId",
    view_cnt: 312351346,
    like_quantity: 7234523463,
    comment_cnt: 45724541354,
  },
  {
    idx: 4,
    status: "",
    category: "一般",
    title: "テストタイトル",
    created_at: "21.01.07",
    donor: "testId",
    view_cnt: 3,
    like_quantity: 7,
    comment_cnt: 0,
  },
  {
    idx: 5,
    status: "",
    category: "一般",
    title: "テストタイトル",
    created_at: "21.01.07",
    donor: "testId",
    view_cnt: 3,
    like_quantity: 7,
    comment_cnt: 4,
  },
];
